### ISSUE TITLE
API Authentication

### ISSUE THREAD

**Issue by MasterHahn04** [Letsu/evping#11]
How we make sure that the User should read the Values that he request?
- API-Key?
- Username and Password?

When we use Username and Password to Authenticate the User we can also implement that a specific User only can see specific Hosts

**Comment by Letsu** [comment]
In my oppinum we should let authentification to be handelt by the user, using a reverse proxy for authentification or at the most only implement a optional middleware for passing a username & password for basic auth authentification over a enviorment variable.

Adding API Keys and/or user authentication adds a huge overhead to implement it properly, since we would need to manage users, groups, password and keys securely.
